# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# получение объявлений пользователем
GET {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 2565a564bad72f7120d2156e1d8f8020631f7f15

###

# получение объявлений администратором
GET {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token fb3de5d24e93b2c7866f0901738730a707e07844

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 2565a564bad72f7120d2156e1d8f8020631f7f15

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token fb3de5d24e93b2c7866f0901738730a707e07844

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2022-11-23
Content-Type: application/json

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=CLOSED
Content-Type: application/json
Authorization: Token fb3de5d24e93b2c7866f0901738730a707e07844

###

# избранное
GET {{baseUrl}}/advertisements/favourites/
Content-Type: application/json
Authorization: Token 2565a564bad72f7120d2156e1d8f8020631f7f15

###

# добавить в избранное
POST {{baseUrl}}/advertisements/add_into_favourites/
Content-Type: application/json
Authorization: Token 2565a564bad72f7120d2156e1d8f8020631f7f15

{
  "id": 5
}

###

# удаление из избранного
DELETE {{baseUrl}}/advertisements/remove_from_favourites/
Content-Type: application/json
Authorization: Token 2565a564bad72f7120d2156e1d8f8020631f7f15

{
  "id": 5
}

###